#!/bin/bash

# Monster Vault - Setup Script
# Instrua o usuário a seguir estes passos para inicializar o projeto

echo "🔥 Monster Vault - Setup Inicial"
echo "=================================="
echo ""
echo "1️⃣  Você precisa ter uma conta no Firebase Console"
echo "   Acesse: https://console.firebase.google.com/"
echo ""
echo "2️⃣  Crie um novo projeto Firebase"
echo ""
echo "3️⃣  Ative os seguintes serviços:"
echo "   - Authentication (Email/Senha e Google)"
echo "   - Cloud Firestore"
echo ""
echo "4️⃣  Configure as seguintes Security Rules no Firestore:"
echo ""
echo "   rules_version = '2';"
echo "   service cloud.firestore {"
echo "     match /databases/{database}/documents {"
echo "       match /users/{userId} {"
echo "         allow read, write: if request.auth.uid == userId;"
echo "         match /collection/{canId} {"
echo "           allow read, write: if request.auth.uid == userId;"
echo "         }"
echo "         match /wishlist/{canId} {"
echo "           allow read, write: if request.auth.uid == userId;"
echo "         }"
echo "       }"
echo "       match /cans/{canId} {"
echo "         allow read: if request.auth != null;"
echo "         allow write: if false;"
echo "       }"
echo "       match /catalogMetadata/{document=**} {"
echo "         allow read: if request.auth != null;"
echo "         allow write: if false;"
echo "       }"
echo "     }"
echo "   }"
echo ""
echo "5️⃣  Copie as credenciais do projeto"
echo ""
echo "6️⃣  Crie um arquivo .env.local com as credenciais:"
echo ""
echo "   cp .env.example .env.local"
echo ""
echo "   E preencha com seus dados:"
echo "   VITE_FIREBASE_API_KEY=xxxxx"
echo "   VITE_FIREBASE_AUTH_DOMAIN=xxxxx"
echo "   VITE_FIREBASE_PROJECT_ID=xxxxx"
echo "   VITE_FIREBASE_STORAGE_BUCKET=xxxxx"
echo "   VITE_FIREBASE_MESSAGING_SENDER_ID=xxxxx"
echo "   VITE_FIREBASE_APP_ID=xxxxx"
echo ""
echo "7️⃣  Para adicionar dados de teste, você pode:"
echo "   - Usar o Firebase Console para adicionar manualmente"
echo "   - Criar um script de seed (próxima funcionalidade)"
echo ""
echo "8️⃣  Instale as dependências:"
echo ""
echo "   npm install"
echo ""
echo "9️⃣  Inicie o servidor de desenvolvimento:"
echo ""
echo "   npm run dev"
echo ""
echo "🎉 Pronto! A aplicação estará disponível em http://localhost:5173"
echo ""
echo "=================================="
echo "Precisa de ajuda? Consulte o README.md"
